# Project Information
site_name: Coding Guidelines
site_description: Coding Guidelines
repo_url: https://github.com/joshminnie/style-guide

# Copyright
copyright: '&copy;2017 <a href="https://nissisolutions.com" target="_blank">Nissi Solutions</a>'

# Theme
theme: 'material'
# http://squidfunk.github.io/mkdocs-material/getting-started/#full-example

# Options
extra:
  logo: 'assets/images/nissisolutions-logo.png'
  font:
    text: 'Lato'
  palette:
    primary: 'light blue'
    accent: 'light blue'

# Extensions
markdown_extensions:
  - admonition
  - codehilite

# Documentation
pages:
  - 'Home': 'index.md'
  - 'Stylesheet Guidelines': 'guidelines.md'
